apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: wajguqlod-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-61cc99615f.7v4o.p3.openshiftapps.com/rhtap/rhtap-qe:4d9c91edea49eb38c606f80ea2047e77fa327253@sha256:b216f74a90dc7f68c6a2f88ff1773ec489de0ba610f5ce23c04da46a8c1cdc82
        name: container-image  
